# Generated by Django 4.0.3 on 2022-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='latitude',
            field=models.CharField(default=1122, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geodata',
            name='longitude',
            field=models.CharField(default=1122, max_length=255),
            preserve_default=False,
        ),
    ]
