# Generated by Django 4.0.3 on 2022-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_geodata_latitude_geodata_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
